services:
  liminal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    volumes:
      - liminal_data:/data
    environment:
      - PUID=${PUID:-911}
      - PGID=${PGID:-911}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_PATH=/data/liminal.db
      - UPLOAD_DIR=/data/uploads/images
      - PHX_SERVER=true
      - PHX_HOST=${PHX_HOST:-localhost}
      # - PHX_CHECK_ORIGINS=//domain2.com,//domain3.com
      - PORT=${PORT:-4000}
      - POOL_SIZE=${POOL_SIZE:-5}
      - SIGNUPS_ENABLED=${SIGNUPS_ENABLED:-false}
    restart: unless-stopped

volumes:
  liminal_data:
    driver: local
